# Welcome to Serverless!

service: xport-convert
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

#  stage: dev
#  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:GetObjectAcl"      
          Resource:
            - "arn:aws:s3:::clairways-xport-convert/*"

functions:
  sasconvert: # A function to convert csv files to SAS XPT format
    handler: handler.convert
    timeout: 5  # Timeout in seconds
    memorySize: 256 # in MB, default is 1024
    events:
      - s3:
          bucket: clairways-xport-convert
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
            - suffix: .csv
          existing: true

plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    useStaticCache: false